[build-system]
requires = [
    'setuptools >= 75',
]
build-backend = 'setuptools.build_meta'

[project]
name = 'caf'
version = '0.0.1'
requires-python = '>=3.10'

[project.scripts]
caf = "caf.__main__:main"

[project.optional-dependencies]
test = ['pytest', 'coverage', 'pytest-cov']